const tseslint = require("typescript-eslint");

module.exports = tseslint.config(
    {
        ignores: ["dist/**", "node_modules/**"],
    },
    ...tseslint.configs.recommended,
    {
        files: ["src/**/*.ts"],
        languageOptions: {
            parserOptions: {
                sourceType: "module",
            },
        },
        rules: {
            "@typescript-eslint/adjacent-overload-signatures": "error",
            "@typescript-eslint/array-type": ["error", { default: "array" }],
            "@typescript-eslint/consistent-type-assertions": "error",
            "@typescript-eslint/explicit-function-return-type": "off",
            "@typescript-eslint/explicit-module-boundary-types": "off",
            "@typescript-eslint/member-ordering": "off",
            "@typescript-eslint/no-empty-function": "error",
            "@typescript-eslint/no-explicit-any": "off",
            "@typescript-eslint/no-namespace": "off",
            "@typescript-eslint/no-parameter-properties": "off",
            "@typescript-eslint/no-shadow": ["error", { hoist: "all" }],
            "@typescript-eslint/no-unused-expressions": "error",
            "@typescript-eslint/no-use-before-define": "off",
            "@typescript-eslint/prefer-for-of": "error",
            "@typescript-eslint/prefer-function-type": "error",
            "@typescript-eslint/prefer-namespace-keyword": "error",
            "@typescript-eslint/triple-slash-reference": [
                "error",
                {
                    path: "always",
                    types: "prefer-import",
                    lib: "always",
                },
            ],
            "@typescript-eslint/unified-signatures": "error",
            "comma-dangle": "error",
            eqeqeq: ["error", "smart"],
            "guard-for-in": "error",
            "max-len": ["error", { code: 260 }],
            "new-parens": "error",
            "no-caller": "error",
            "no-cond-assign": "error",
            "no-console": "off",
            "no-debugger": "error",
            "no-empty": "error",
            "no-eval": "error",
            "no-new-wrappers": "error",
            "no-shadow": "off",
            "no-trailing-spaces": "error",
            "no-unsafe-finally": "error",
            "no-unused-expressions": "off",
            "no-unused-labels": "error",
            "no-use-before-define": "off",
            "no-var": "error",
            "one-var": ["error", "never"],
            "prefer-const": "error",
            "spaced-comment": ["error", "always", { markers: ["/"] }],
            "use-isnan": "error",
        },
    },
);
